# Generated by Django 3.2.5 on 2021-07-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_list_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='slug',
        ),
    ]
